global:
  scrape_interval: 30s
  evaluation_interval: 10s

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: "alertmanager"
    static_configs:
      - targets: [ 'alertmanager:9093' ]

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'blackbox_2xx'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
        - https://esxi.EXAMPLE.COM
        - https://EXAMPLE.COM
        - https://auth.EXAMPLE.COM
        - https://metrics.EXAMPLE.COM
        - https://monitoring.EXAMPLE.COM
        - https://docker.EXAMPLE.COM
        - https://cloud.EXAMPLE.COM
        - https://discord.EXAMPLE.COM
        - https://loading.EXAMPLE.COM
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_basic_auth'
    metrics_path: /probe
    params:
      module: [ http_basic_auth ]
    static_configs:
      - targets:
        - https://proxy.EXAMPLE.COM
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "docker"
    static_configs:
      - targets: [ 'localhost:9323' ]

  - job_name: "traefik"
    static_configs:
      - targets: [ 'traefik:8080' ]

